using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class ControlManager : MonoBehaviour
{
    private IControlScheme currentControlScheme;
    private KeyboardControl keyboardControl;
    private UDPControl udpControl;
    

    [SerializeField]
    private TextAsset configFile; // TextAsset縺ｨ縺励※JSON繝輔ぃ繧､繝ｫ繧呈欠螳・
    private CustomCharacterController characterController;

    public Camera firstCamera;
    public Camera secondCamera;

    void Start()
    {
        ControlConfig config = ControlConfigLoader.LoadConfig(configFile);

        keyboardControl = new KeyboardControl();
        udpControl = new UDPControl(config.udpSettings.ipAddress, config.udpSettings.port);

        // 繧ｭ繝｣繝ｩ繧ｯ繧ｿ繝ｼ繧ｳ繝ｳ繝医Ο繝ｼ繝ｩ繝ｼ縺ｫmovementData繧定ｨｭ螳・        characterController = GetComponent<CustomCharacterController>();
        if (characterController != null)
        {
            characterController.InitMovementData(config.movementData);
            keyboardControl.OnSetMove += characterController.SetMove;
            keyboardControl.OnSetRotate += characterController.SetRotate;
            udpControl.OnSetMove += characterController.SetMove;
            udpControl.OnSetRotate += characterController.SetRotate;

            Debug.Log("Delegates assigned");
        }
        else
        {
            Debug.LogError("CustomCharacterController not found on GameObject");
        }

        // 蛻晄悄蛻ｶ蠕｡譁ｹ豕輔ｒ險ｭ螳壹ヵ繧｡繧､繝ｫ縺ｫ蝓ｺ縺･縺・※險ｭ螳・        switch (config.controlType.ToLower())
        {
            case "keyboard":
                currentControlScheme = keyboardControl;
                Debug.Log("input mode : Keyboard");
                break;
            case "udp":
                currentControlScheme = udpControl;
                Debug.Log("input mode : UDP");
                break;
            default:
                Debug.LogError("Unknown control type in config");
                break;
        }

        // 譛蛻昴・繧ｫ繝｡繝ｩ繧呈怏蜉ｹ縺ｫ縺吶ｋ
        firstCamera.gameObject.SetActive(true);
        // 莠後▽逶ｮ縺ｮ繧ｫ繝｡繝ｩ繧堤┌蜉ｹ縺ｫ縺吶ｋ
        secondCamera.gameObject.SetActive(false);
    }

    void Update()
    {
        // 迴ｾ蝨ｨ縺ｮ蛻ｶ蠕｡譁ｹ豕輔ｒ譖ｴ譁ｰ
        currentControlScheme.UpdateControl();

        // 莉ｻ諢上・繧ｭ繝ｼ縺ｧ蛻ｶ蠕｡譁ｹ豕輔ｒ蛻・ｊ譖ｿ縺・        if (Input.GetKeyDown(KeyCode.U))
        {
            if (characterController.IsUDPControlActive)
            {
                currentControlScheme = keyboardControl;
                characterController.SetMove(0.0f);
                Debug.Log("input mode : Keyboard");
            }
            else
            {
                currentControlScheme = udpControl;
                characterController.SetMove(1.0f);

                Debug.Log("input mode : UDP");
            }
            characterController.IsUDPControlActive = !characterController.IsUDPControlActive;
                               
        }

        if (Input.GetKeyDown(KeyCode.C))
        {
            firstCamera.gameObject.SetActive(!firstCamera.gameObject.activeSelf);
            secondCamera.gameObject.SetActive(!secondCamera.gameObject.activeSelf);
        }
    }
}
